# Numpy

In [1]:
!pip install numpy
!pip install pandas

In [2]:
import numpy as np

In [3]:
#Array creation

In [4]:
x= np.array(10)

In [5]:
type(x)

numpy.ndarray

In [6]:
#Zero dimensional array
x.ndim

0

In [7]:
#One dimensional array
x= np.array([10,20,30])
print(type(x))
x.ndim

<class 'numpy.ndarray'>


1

In [8]:
#Two dimensional array
x= np.array([[11,22,33]])
print(type(x))
x.ndim

<class 'numpy.ndarray'>


2

In [9]:
#Change the data type of array elements
a= np.array([[1,12,59,97,'Jupyter']])
a

array([['1', '12', '59', '97', 'Jupyter']], dtype='<U11')

In [10]:
b= np.array([1,2,3,4,5],dtype='float')
b

array([1., 2., 3., 4., 5.])

In [11]:
x= np.arange(21,31,2)

In [12]:
x= np.linspace(10,15,20,retstep=True)
x

(array([10.        , 10.26315789, 10.52631579, 10.78947368, 11.05263158,
        11.31578947, 11.57894737, 11.84210526, 12.10526316, 12.36842105,
        12.63157895, 12.89473684, 13.15789474, 13.42105263, 13.68421053,
        13.94736842, 14.21052632, 14.47368421, 14.73684211, 15.        ]),
 0.2631578947368421)

In [13]:
x= np.zeros([2,6])
x

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.random.rand(2,2)

array([[0.93009753, 0.86677698],
       [0.60033265, 0.87986889]])

In [16]:
np.random.randint(1,5,10)

array([2, 1, 1, 4, 1, 4, 4, 4, 3, 3])

In [17]:
np.random.randn(5,6)

array([[-1.26076383, -1.17625291, -0.35205415,  1.77902788,  0.2688694 ,
        -1.83638   ],
       [-0.95185229,  0.63124924, -0.78447353,  1.02810439, -2.93352729,
         0.93582177],
       [ 0.50510375, -1.07304161,  0.74991367,  0.11401895, -0.3263032 ,
        -2.10088551],
       [ 0.55243769, -0.14438095,  0.09299682, -1.97047184,  1.48961552,
         0.02850037],
       [-1.16421208, -0.2036633 ,  0.33763018,  0.62552395,  0.62549077,
        -0.54422999]])

Slicing and Indexing of arrays

In [18]:
a= np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a.ndim

1

In [20]:
a[4:7]

array([5, 6, 7])

In [21]:
a[4: ]

array([5, 6, 7, 8, 9])

In [22]:
a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a[1,1]

5

In [24]:
a[0:,1]

array([2, 5])

In [25]:
a[:,1]

array([2, 5])

In [26]:
a[0:1,1:2]

array([[2]])

In [27]:
a[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
a[:,1]

array([2, 5])

In [29]:
a[0:1,1:2]

array([[2]])

In [30]:
a[:,1:]

array([[2, 3],
       [5, 6]])

In [31]:
#1 and 6
a[0:1,1:2]

array([[2]])

In [32]:
#1 and 6 
a

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
a[[0,1],[0,2]]

array([1, 6])

In [34]:
a[1,2]

6

Reshaping the arrays

In [35]:
a= np.random.rand(5,5)
a

array([[0.30431681, 0.14389121, 0.2233826 , 0.22562351, 0.04287936],
       [0.37800647, 0.46946284, 0.10830083, 0.33500273, 0.42435317],
       [0.53174637, 0.78117198, 0.99416556, 0.34198423, 0.24352168],
       [0.24948397, 0.04460643, 0.13350743, 0.42405061, 0.54918721],
       [0.14974037, 0.22749797, 0.41160758, 0.54027209, 0.41953181]])

In [36]:
a.shape

(5, 5)

In [37]:
a.reshape(1,25)

array([[0.30431681, 0.14389121, 0.2233826 , 0.22562351, 0.04287936,
        0.37800647, 0.46946284, 0.10830083, 0.33500273, 0.42435317,
        0.53174637, 0.78117198, 0.99416556, 0.34198423, 0.24352168,
        0.24948397, 0.04460643, 0.13350743, 0.42405061, 0.54918721,
        0.14974037, 0.22749797, 0.41160758, 0.54027209, 0.41953181]])

In [38]:
a.reshape(25,1)

array([[0.30431681],
       [0.14389121],
       [0.2233826 ],
       [0.22562351],
       [0.04287936],
       [0.37800647],
       [0.46946284],
       [0.10830083],
       [0.33500273],
       [0.42435317],
       [0.53174637],
       [0.78117198],
       [0.99416556],
       [0.34198423],
       [0.24352168],
       [0.24948397],
       [0.04460643],
       [0.13350743],
       [0.42405061],
       [0.54918721],
       [0.14974037],
       [0.22749797],
       [0.41160758],
       [0.54027209],
       [0.41953181]])

In [39]:
a.reshape(5,-1)

array([[0.30431681, 0.14389121, 0.2233826 , 0.22562351, 0.04287936],
       [0.37800647, 0.46946284, 0.10830083, 0.33500273, 0.42435317],
       [0.53174637, 0.78117198, 0.99416556, 0.34198423, 0.24352168],
       [0.24948397, 0.04460643, 0.13350743, 0.42405061, 0.54918721],
       [0.14974037, 0.22749797, 0.41160758, 0.54027209, 0.41953181]])

In [40]:
a.reshape(-1,25)

array([[0.30431681, 0.14389121, 0.2233826 , 0.22562351, 0.04287936,
        0.37800647, 0.46946284, 0.10830083, 0.33500273, 0.42435317,
        0.53174637, 0.78117198, 0.99416556, 0.34198423, 0.24352168,
        0.24948397, 0.04460643, 0.13350743, 0.42405061, 0.54918721,
        0.14974037, 0.22749797, 0.41160758, 0.54027209, 0.41953181]])

In [41]:
#Aggregate functions
a

array([[0.30431681, 0.14389121, 0.2233826 , 0.22562351, 0.04287936],
       [0.37800647, 0.46946284, 0.10830083, 0.33500273, 0.42435317],
       [0.53174637, 0.78117198, 0.99416556, 0.34198423, 0.24352168],
       [0.24948397, 0.04460643, 0.13350743, 0.42405061, 0.54918721],
       [0.14974037, 0.22749797, 0.41160758, 0.54027209, 0.41953181]])

In [42]:
a.min()

0.04287935917308916

In [43]:
a.max()

0.9941655577984811

In [44]:
a.mean()

0.3478917925097633

In [45]:
a.std()

0.21818726141040046

In [46]:
a.var()

0.047605681041770424

# stacking
1.Vertical stacking, 
2.Horizontal stacking

In [47]:
a= np.array([4,5,6,7,8,9])
b= np.array([10,20,30,40,50,60])

In [48]:
np.vstack([a,b])

array([[ 4,  5,  6,  7,  8,  9],
       [10, 20, 30, 40, 50, 60]])

In [49]:
np.hstack([a,b])

array([ 4,  5,  6,  7,  8,  9, 10, 20, 30, 40, 50, 60])